include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true # const [] instead of []
    prefer_const_declarations: true # const for local variables
    prefer_final_fields: true # final for fields that don't change
